import Link from "next/link";
import { PDF_WORKFLOWS, workflowPath } from "@/lib/content/pdf-workflows";
import { collectionSchema, pseoMetadata } from "@/lib/content/pseo-metadata";
import { JsonLd } from "@/components/seo/JsonLd";
import { getBreadcrumbSchema } from "@/lib/seo";
export const metadata = pseoMetadata("PDF Workflows: Combine Tasks in One Place", "Merge and compress PDFs, add continuous page numbers, watermark a packet or combine Word files. Run both steps locally and download one PDF.", "/pdf-workflows");
export default function Page() {
  return <div className="container mx-auto max-w-6xl px-4 py-12"><JsonLd data={[collectionSchema("PDF workflows", "/pdf-workflows", PDF_WORKFLOWS.map(row => ({ title: row.title, path: workflowPath(row) }))), getBreadcrumbSchema([{ name: "PDFPilot", path: "/" }, { name: "PDF workflows", path: "/pdf-workflows" }])]} /><header className="max-w-3xl"><p className="text-sm font-semibold text-primary">Two tasks. One PDF download.</p><h1 className="mt-3 text-4xl font-bold tracking-tight md:text-5xl">PDF workflows</h1><p className="mt-5 text-lg text-muted-foreground">Choose the result you need. Each workflow runs both steps in your browser and passes the output directly into the next step.</p><p className="mt-4 text-sm text-muted-foreground">Free · no sign-up · no file uploads to a server</p></header><ul className="mt-10 grid gap-6 md:grid-cols-2">{PDF_WORKFLOWS.map(row => <li key={row.slug} className="rounded-2xl border bg-card p-6 text-card-foreground"><p className="text-xs font-medium text-muted-foreground">{row.input.toUpperCase()} → PDF</p><h2 className="mt-2 text-xl font-semibold"><Link href={workflowPath(row)}>{row.title}</Link></h2><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{row.description}</p><ol className="mt-4 list-decimal space-y-1 ps-5 text-sm">{row.steps.map(step => <li key={step}>{step}</li>)}</ol><Link href={workflowPath(row)} className="mt-5 inline-block font-semibold text-primary">Open workflow →</Link></li>)}</ul><div className="mt-10 flex flex-wrap gap-6 text-sm"><Link href="/templates" className="underline">Create a document from a template</Link><Link href="/templates/conversions" className="underline">Browse conversion presets</Link><Link href="/compare/compress-pdf-vs-split-pdf" className="underline">Compress or split: choose the right tool</Link></div></div>;
}
