const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {load}=require('../scripts/load-pseo-modules.cjs');
const {classifyKeyword,normalizeKeyword}=load('src/lib/pseo/classify.ts');
const {CAPABILITIES,CAPABILITY_BY_ID,privacyCopy}=load('src/lib/pseo/capabilities.ts');
const {generateCandidate,fingerprint}=load('src/lib/pseo/content.ts');
const {qualityIssues,catalogIssues}=load('src/lib/pseo/quality.ts');
const {pageSchema}=load('src/lib/pseo/schema.ts');
const {parseCsv,importCsv,writeJson}=require('../scripts/pseo-import.cjs');
const {build,reservedSlugs}=require('../scripts/pseo.cjs');
function fixture(t,csv='Keyword,Volume,KD %,CPC\nPNG to PDF,100,20,0.3\n'){
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pseo-engine-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));
 const file=path.join(dir,'keywords.csv');fs.writeFileSync(file,csv);const data=path.join(dir,'data');
 const result=importCsv(file,data,{market:'IN',language:'en',date:'2026-09-28'});return {dir,file,data,result};
}
function reviewed(page){return {status:'approved',reviewer:'QA',reviewedAt:'2026-09-28',contentFingerprint:page.contentFingerprint,capabilityFingerprint:fingerprint(CAPABILITY_BY_ID.get(page.baseToolId)),distinctUtility:'Verified format handling, image proportions and transparency checks.',evidence:['tests/pseo-engine.test.cjs']};}

test('exactly 26 public tools, no hidden tool becomes eligible',()=>{assert.equal(CAPABILITIES.length,26);assert.equal(CAPABILITY_BY_ID.has('unlock-pdf'),false);assert.equal(classifyKeyword('unlock pdf').family,'unsupported');});
test('source capabilities prevent exact target promises and unsupported images',()=>{for(const q of ['webp to pdf','heic to pdf','tiff to pdf','pdf to dwg','doc to pdf'])assert.equal(classifyKeyword(q).family,'unsupported',q);assert.equal(CAPABILITY_BY_ID.get('compress-pdf').supportsExactTargetSize,false);});
test('numeric synonyms cluster into one intent',()=>{const q=['compress pdf to 100kb','compress pdf to 100 kb','reduce pdf to 100kb','reduce pdf size 100kb','make pdf 100 kb'];assert.equal(new Set(q.map(x=>classifyKeyword(x).signature)).size,1);assert.equal(classifyKeyword('compress pdf under 1mb').signature,classifyKeyword('reduce pdf to 1000kb').signature);});
test('core synonyms retain core ownership',()=>{for(const q of ['pdf compressor','compress pdf','combine pdf','merge pdf','jpg to pdf','jpeg to pdf'])assert.equal(classifyKeyword(q).family,'core',q);});
test('classification covers informational, workflow, irrelevant and modifiers',()=>{for(const [q,f]of [['how to merge pdf','informational'],['merge and compress pdf','workflow'],['running shoes','irrelevant'],['merge pdf on mac','platform'],['split pdf iphone','device'],['compress pdf for email','use-case'],['png to pdf','format']])assert.equal(classifyKeyword(q).family,f,q);});
test('BOM, quoted commas, embedded newlines and escaped quotes parse losslessly',()=>{assert.deepEqual(parseCsv('\uFEFFKeyword,Volume\r\n"png, to pdf","1,200"\r\n"line\n""two""",0\r\n').map(x=>x.cells),[['Keyword','Volume'],['png, to pdf','1,200'],['line\n"two"','0']]);assert.throws(()=>parseCsv('Keyword\n"broken'),/Unclosed/);});
test('aliases, missing metrics, invalid rows and unknown columns are preserved',t=>{const x=fixture(t,'Search Query;Search Volume;Keyword Difficulty;CPC (USD);Custom\npng to pdf;1.2K;25;0.25;kept\n;bad;130;;empty\n');const r=build(x.data);assert.equal(r.ledger.length,2);assert.equal(r.ledger[0].searchVolume,1200);assert.equal(r.ledger[0].raw.Custom,'kept');assert.equal(r.ledger[1].searchVolume,null);assert.equal(r.ledger[1].keywordDifficulty,null);assert.equal(r.ledger[1].status,'irrelevant');});
test('every source row has original file, market and physical row provenance',t=>{const x=fixture(t,'Keyword,Volume\npng to pdf,1\n,\nunknown pdf task,2\n');const r=build(x.data);assert.equal(r.ledger.length,3);assert.deepEqual(r.ledger.map(r=>r.sourceRowId),[2,3,4]);assert.ok(r.ledger.every(r=>r.sourceFile==='keywords.csv'&&r.sourceMarket==='IN'));});
test('raw source is byte-identical; repeat import is idempotent',t=>{const x=fixture(t);assert.equal(importCsv(x.file,x.data,{market:'IN',language:'en',date:'2026-09-28'}).reimport,true);const state=JSON.parse(fs.readFileSync(path.join(x.data,'manifests/state.json')));assert.equal(state.sources.length,1);assert.deepEqual(fs.readFileSync(path.join(x.data,state.sources[0].rawPath)),fs.readFileSync(x.file));});
test('incremental countries retain separate observations without country URLs',t=>{const x=fixture(t);importCsv(x.file,x.data,{market:'US',language:'en',date:'2026-09-28'});const r=build(x.data);assert.equal(r.candidates.length,1);assert.equal(r.candidates[0].demand.length,2);assert.deepEqual(r.candidates[0].provenance.map(p=>p.sourceMarket).sort(),['IN','US']);assert.equal(r.candidates[0].canonicalUrl,'https://pdfpilot.net/png-to-pdf');assert.equal(r.report.duplicates,1);});
test('build is deterministic and does not invent metrics',t=>{const x=fixture(t,'Keyword\npng to pdf\n');const a=build(x.data);const b=build(x.data);assert.deepEqual(a,b);assert.equal(a.candidates[0].demand[0].searchVolume,null);});
test('no source market is inferred; unfamiliar/ambiguous headers fail closed',t=>{const x=fixture(t);assert.throws(()=>importCsv(x.file,x.data,{}),/market/);fs.writeFileSync(x.file,'Foo,Bar\nx,y\n');assert.throws(()=>importCsv(x.file,x.data,{market:'US'}),/keyword header/);fs.writeFileSync(x.file,'Keyword,Query\nx,y\n');assert.throws(()=>importCsv(x.file,x.data,{market:'US'}),/Ambiguous/);});
test('drafts and unsupported constraints cannot enter runtime manifest',t=>{const x=fixture(t,'Keyword\npng to pdf\ncompress pdf to 100kb\n');const r=build(x.data);assert.equal(r.approved.length,0);assert.ok(r.candidates.find(p=>p.pageType==='size').rejectionReason.includes('exact_target_not_supported_by_core_tool'));});
test('review is fingerprint-bound; capabilities and contents cannot change silently',t=>{const x=fixture(t);const page=build(x.data).candidates[0];const review=reviewed(page);assert.deepEqual(qualityIssues(page,reservedSlugs(),review),[]);assert.ok(qualityIssues({...page,contentFingerprint:'changed'},reservedSlugs(),review).includes('stale_content_review'));assert.ok(qualityIssues(page,reservedSlugs(),{...review,capabilityFingerprint:'changed'}).includes('stale_capability_review'));});
test('valid reviewed page builds; incremental imports preserve primary and URL',t=>{const x=fixture(t);let page=build(x.data).candidates[0];writeJson(path.join(x.data,'manifests/reviews.json'),{[page.intentSignature]:reviewed(page)});let r=build(x.data);assert.equal(r.approved.length,1);fs.writeFileSync(x.file,'Keyword,Volume\nfree png to pdf,9999\n');importCsv(x.file,x.data,{market:'GB',language:'en',date:'2026-09-28'});r=build(x.data);assert.equal(r.approved.length,1);assert.equal(r.approved[0].primaryKeyword,page.primaryKeyword);assert.equal(r.approved[0].slug,page.slug);});
test('device pages require matching end-to-end platform evidence',t=>{const x=fixture(t,'Keyword\nmerge pdf on mac\n');const page=build(x.data).candidates[0];assert.ok(qualityIssues(page,reservedSlugs(),reviewed(page)).includes('platform_end_to_end_verification_required'));});
test('hybrid processing cannot inherit local-only claims',t=>{assert.equal(CAPABILITY_BY_ID.get('html-to-pdf').processingMode,'hybrid');assert.match(privacyCopy('excel-to-xml'),/server/);const x=fixture(t,'Keyword\nhtml to pdf on mac\n');const page=build(x.data).candidates[0];page.intro='Your files never leave your device';assert.ok(qualityIssues(page,reservedSlugs(),reviewed(page)).includes('unverified_privacy_claim'));});
test('unknown localization is held without duplicated English URLs',t=>{const x=fixture(t);importCsv(x.file,x.data,{market:'ES',language:'es',date:'2026-09-28'});const r=build(x.data);assert.equal(r.ledger.find(r=>r.language==='es').status,'review_required');assert.equal(r.candidates.length,1);});
test('route collisions, invalid links, duplicate titles and fixture leakage fail QA',t=>{const x=fixture(t);const p=build(x.data).candidates[0];p.indexable=true;p.qualityStatus='approved';assert.ok(qualityIssues({...p,slug:'merge-pdf'},reservedSlugs(),reviewed(p)).includes('route_collision'));assert.ok(catalogIssues([p,{...p,slug:'other',canonicalUrl:'https://pdfpilot.net/other'}]).some(x=>x.startsWith('duplicate_intentSignature')));assert.ok(catalogIssues([{...p,fixture:true}]).some(x=>x.startsWith('nonindexable')));assert.ok(catalogIssues([{...p,relatedPages:['missing']}]).some(x=>x.startsWith('invalid_related')));});
test('schema rejects malformed records and fixtures never leak into production',()=>{assert.throws(()=>pageSchema.parse({slug:'../escape'}));assert.ok(require('../src/lib/content/pseo-pages.json').every(p=>!p.fixture&&p.indexable&&['approved','published'].includes(p.qualityStatus))); assert.equal(normalizeKeyword('  COMPRESS PDF to 100 KB '),'compress pdf to 100kb');});
test('sitemaps exclude drafts and split large families below sitemap limits',t=>{const {pseoSitemapChunks}=load('src/lib/pseo/sitemap.ts');const x=fixture(t);const p=build(x.data).candidates[0];assert.equal(pseoSitemapChunks([p]).length,0);const pages=Array.from({length:5001},(_,i)=>({...p,slug:'png-'+i,indexable:true,qualityStatus:'approved'}));const chunks=pseoSitemapChunks(pages);assert.deepEqual(chunks.map(c=>c.pages.length),[5000,1]);assert.equal(pseoSitemapChunks([{...pages[0],fixture:true}]).length,0);});
test('raw-source recovery does not overwrite or discard a prior file',t=>{const x=fixture(t);const stateFile=path.join(x.data,'manifests/state.json');fs.writeFileSync(stateFile,'{"version":1,"sources":[]}');assert.equal(importCsv(x.file,x.data,{market:'IN',language:'en',date:'2026-09-28'}).reimport,false);assert.equal(build(x.data).ledger.length,1);});
test('tampered normalized data cannot silently change demand or provenance',t=>{const x=fixture(t);const f=path.join(x.data,'normalized',x.result.id+'.jsonl');fs.appendFileSync(f,'\n');assert.throws(()=>build(x.data),/Normalized source integrity/);});
test('unsupported exact-size intent cannot be approved by an editorial review',t=>{const x=fixture(t,'Keyword\ncompress pdf to 100kb\n');const p=build(x.data).candidates[0];assert.ok(qualityIssues(p,reservedSlugs(),reviewed(p)).includes('exact_target_not_supported_by_core_tool'));});
test('every public core keyword has exactly its existing tool as owner',()=>{for(const t of CAPABILITIES){const c=classifyKeyword(t.canonicalCoreKeyword);assert.equal(c.family,'core',t.toolId);assert.equal(c.toolId,t.toolId);}});

test('SEMrush ranking exports map intent and SERP aliases while preserving ranking observations',t=>{const x=fixture(t,'Keyword,Search Volume,Keyword Intents,SERP Features by Keyword,Position,URL\npng to pdf,100,commercial,"Video, AI overview",2,https://example.com/tool\n');const r=build(x.data).ledger[0];assert.equal(r.intent.family,'format');const normalized=JSON.parse(fs.readFileSync(path.join(x.data,'normalized',x.result.id+'.jsonl'),'utf8').trim());assert.equal(normalized.intent,'commercial');assert.deepEqual(normalized.serpFeatures,['Video','AI overview']);assert.equal(normalized.raw.Position,'2');assert.equal(normalized.raw.URL,'https://example.com/tool');});
test('SEMrush traffic count and percentage remain separate raw columns',t=>{const x=fixture(t,'Keyword,Traffic,Traffic (%)\npng to pdf,400,1.25\n');const row=build(x.data).ledger[0];assert.equal(row.raw.Traffic,'400');assert.equal(row.raw['Traffic (%)'],'1.25');});
test('real export wording preserves core ownership and does not parse connecting words as formats',()=>{for(const [q,id]of [['merge pdfs','merge-pdf'],['pdf combiner','merge-pdf'],['image to pdf','jpg-to-pdf'],['delete pages from pdf document','delete-pages'],['convert html file to pdf','html-to-pdf']]){const c=classifyKeyword(q);assert.equal(c.family,'core',q);assert.equal(c.toolId,id,q);}assert.equal(classifyKeyword('how to convert a pdf to a word document').toolId,'pdf-to-word');});
test('foreign queries and competitor names are held without using competitor URLs as language evidence',()=>{for(const q of ['convertir pdf a word','pdf kaise banaye','word į pdf','pdf se word','पीडीएफ pdf'])assert.equal(classifyKeyword(q).reason,'localization_review',q);assert.equal(classifyKeyword('png to pdf ilovepdf').reason,'competitor_brand_review');});
test('unreviewed modifiers stay distinct from verified capability gaps',()=>{assert.equal(classifyKeyword('merge pdf unusual requirement').reason,'unreviewed_modifier');assert.equal(classifyKeyword('merge pdf unusual requirement').family,'informational');assert.equal(classifyKeyword('heic to pdf').family,'unsupported');assert.equal(classifyKeyword('png to pdf 100kb').family,'size');});
test('research metrics never multiply volume for competitor URL duplicates',()=>{const {metrics}=require('../scripts/pseo-research.cjs');const r=metrics([{normalizedKeyword:'png to pdf',searchVolume:100,keywordDifficulty:20,cpc:.5,raw:{Position:'2',Traffic:'8',URL:'https://example.com/a'}},{normalizedKeyword:'png to pdf',searchVolume:100,keywordDifficulty:20,cpc:.5,raw:{Position:'5',Traffic:'3',URL:'https://example.com/b'}}]);assert.equal(r.observations,2);assert.equal(r.uniqueKeywords,1);assert.equal(r.largestKeywordVolume,100);assert.deepEqual(r.keywords[0].searchVolumeValues,[100]);assert.equal(r.keywords[0].maximumRankingTraffic,8);});
test('real export ownership avoids fake formats, editing conversion confusion and app promises',()=>{for(const q of ['merge pdf into one','combine pdf into one pdf'])assert.notEqual(classifyKeyword(q).family,'unsupported',q);assert.equal(classifyKeyword('how to add text to a pdf mac').toolId,'edit-pdf');assert.equal(classifyKeyword('pdf full form').reason,'pdf_definition_review');assert.equal(classifyKeyword('pdf unlocker').family,'unsupported');assert.equal(classifyKeyword('pdf to word software for mac').reason,'desktop_or_app_review');assert.equal(classifyKeyword('200kb pdf').family,'size');assert.equal(classifyKeyword('word pdf').toolId,'word-to-pdf');});
test('compound OCR/use-case keywords cannot bypass platform or language verification',()=>{assert.equal(classifyKeyword('scanned pdf to word on android').family,'device');assert.equal(classifyKeyword('whatsapp image to pdf on iphone').family,'device');assert.equal(classifyKeyword('hindi scanned pdf to word').reason,'ocr_language_not_supported');});
test('English articles and loanwords are not mistaken for foreign-language intent',()=>{assert.equal(classifyKeyword('compress a pdf').family,'core');assert.equal(classifyKeyword('merge a pdf').family,'core');assert.equal(classifyKeyword('edit pdf résumé').modifier,'resume');assert.equal(classifyKeyword('merge pdf on iphone se').family,'device');});
test('known multi-tool demand reuses an existing workflow and does not create a competing page',t=>{const x=fixture(t,'Keyword\nmerge and compress pdf\n');const result=build(x.data);assert.equal(result.candidates.length,0);assert.equal(result.ledger[0].status,'existing_workflow_page');assert.equal(result.ledger[0].canonicalUrl,'https://pdfpilot.net/pdf-workflows/merge-and-compress-pdf');});
test('OCR policy enables WASM only on its worker while production JavaScript eval remains blocked',async()=>{const ts=require('typescript');const previous=process.env.NODE_ENV;process.env.NODE_ENV='production';try{const module={exports:{}};const code=ts.transpileModule(fs.readFileSync('next.config.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,esModuleInterop:true,target:ts.ScriptTarget.ES2022}}).outputText;new Function('require','module','exports','__dirname',code)(require,module,module.exports,process.cwd());const headers=await module.exports.default.headers();const global=headers.find(h=>h.source==='/(.*)').headers.find(h=>h.key==='Content-Security-Policy').value;const worker=headers.find(h=>h.source==='/tesseract/worker.min.js').headers[0].value;assert.ok(!global.includes("'wasm-unsafe-eval'"));assert.ok(!global.includes("'unsafe-eval'"));assert.ok(worker.includes("'wasm-unsafe-eval'"));assert.ok(!worker.includes("'unsafe-eval'"));}finally{if(previous===undefined)delete process.env.NODE_ENV;else process.env.NODE_ENV=previous;}});

test('spreadsheet output ownership excludes incidental Excel XML PDF options',()=>{assert.equal(classifyKeyword('xls to pdf').family,'unsupported');assert.equal(classifyKeyword('excel to pdf').toolId,'excel-to-pdf');assert.equal(classifyKeyword('xls to xml').toolId,'excel-to-xml');});
test('common core variants do not create clones and unsupported layouts remain excluded',()=>{for(const q of ['export pdf to word','recover damaged pdf','delete first page pdf','extract individual pdf pages'])assert.equal(classifyKeyword(q).family,'core',q);assert.equal(classifyKeyword('recover deleted pdf').reason,'deleted_file_recovery_not_supported');assert.equal(classifyKeyword('merge 4 pages into one page pdf').reason,'n_up_page_layout_not_supported');});
test('bank statement extraction has one intent and cannot bypass platform review',()=>{for(const q of ['bank statement pdf to excel','convert bank statements pdf to excel'])assert.equal(classifyKeyword(q).modifier,'bank-statements');assert.equal(classifyKeyword('bank statement pdf to excel on windows').family,'platform');});

test('inserting an image format into an existing PDF belongs to editing',()=>{assert.equal(classifyKeyword('add png to pdf').toolId,'edit-pdf');assert.notEqual(classifyKeyword('add png to pdf').family,'format');});

test('scan tool does not claim PDF rasterization input support',()=>{assert.equal(classifyKeyword('pdf to scanned pdf').reason,'pdf_rasterization_not_supported_by_scan_tool');assert.notEqual(classifyKeyword('pdf a scan').family,'core');});
test('deployment validation works without raw research and rejects stale reviewed content',t=>{
 const x=fixture(t);const page=build(x.data).candidates[0];
 writeJson(path.join(x.data,'manifests/reviews.json'),{[page.intentSignature]:reviewed(page)});
 const approved=build(x.data).approved;const manifest=path.join(x.dir,'approved.json');writeJson(manifest,approved);
 fs.rmSync(path.join(x.data,'sources'),{recursive:true});fs.rmSync(path.join(x.data,'normalized'),{recursive:true});
 const {validateRuntime}=require('../scripts/pseo.cjs');
 assert.equal(validateRuntime(x.data,manifest).approvedPages,1);
 const reviews=JSON.parse(fs.readFileSync(path.join(x.data,'manifests/reviews.json')));
 reviews[page.intentSignature].contentFingerprint='stale';writeJson(path.join(x.data,'manifests/reviews.json'),reviews);
 assert.throws(()=>validateRuntime(x.data,manifest),/stale_content_review/);
});
