import Link from "next/link";
import { DOCUMENT_CATEGORIES, DOCUMENT_TEMPLATES, documentTemplatePath, type DocumentTemplate } from "@/lib/content/document-templates";
import { collectionSchema } from "@/lib/content/pseo-metadata";
import { JsonLd } from "@/components/seo/JsonLd";
import { getBreadcrumbSchema } from "@/lib/seo";
import { DocumentTemplateGallery } from "./DocumentTemplateGallery";
export function DocumentTemplateCollection({ category }: { category?: DocumentTemplate["category"] }) {
  const rows = category ? DOCUMENT_TEMPLATES.filter(row => row.category === category) : DOCUMENT_TEMPLATES;
  const title = category ? DOCUMENT_CATEGORIES[category].title : "Free editable PDF templates";
  const path = category ? `/templates/collections/${category}` : "/templates";
  return <div className="container mx-auto max-w-7xl px-4 py-12"><JsonLd data={[collectionSchema(title, path, rows.map(row => ({ title: row.name, path: documentTemplatePath(row) }))), getBreadcrumbSchema([{ name: "PDFPilot", path: "/" }, { name: "PDF templates", path: "/templates" }, ...(category ? [{ name: title, path }] : [])])]} /><header className="max-w-3xl"><p className="text-sm font-semibold text-primary">Plan it. Fill it. Make it a PDF.</p><h1 className="mt-3 text-4xl font-bold tracking-tight md:text-5xl">{title}</h1><p className="mt-5 text-lg text-muted-foreground">{category ? DOCUMENT_CATEGORIES[category].description : "Start with a useful layout for your next meeting, project or plan. Enter your details, choose A4 or Letter and download a fillable PDF, all in your browser."}</p><p className="mt-4 text-sm text-muted-foreground">Free · no sign-up · no document uploads</p></header><nav aria-label="Document template categories" className="mt-7 flex flex-wrap gap-3"><Link href="/templates" className="rounded-full border px-4 py-2 text-sm" aria-current={!category ? "page" : undefined}>All templates</Link>{Object.entries(DOCUMENT_CATEGORIES).map(([key, value]) => <Link key={key} href={`/templates/collections/${key}`} className="rounded-full border px-4 py-2 text-sm" aria-current={category === key ? "page" : undefined}>{value.title.replace(" PDF templates", "")}</Link>)}</nav><DocumentTemplateGallery templates={rows} /><section className="mt-12 rounded-2xl border p-6"><h2 className="text-xl font-semibold">Already have a document?</h2><p className="mt-3 text-muted-foreground">Convert an existing file or combine PDF tasks in one flow.</p><div className="mt-4 flex flex-wrap gap-5"><Link href="/templates/conversions" className="underline">Conversion templates</Link><Link href="/pdf-workflows" className="underline">PDF workflows</Link><Link href="/fill-pdf" className="underline">Fill PDF forms</Link></div></section></div>;
}
