import { generateCandidate, fingerprint } from './content';
import type { Classification } from './classify';
import type { Keyword, PseoPage } from './schema';
import help from '../content/pt-br-tool-help.json';
import { PDF_IMAGE_COPY, PDF_IMAGE_LIMITS } from '../i18n/pdf-image-copy';
export const isPortugueseRecipe = (intent: Classification) => (intent.toolId==='pdf-to-jpg'&&['extract-images','high-quality','pdf-to-png'].includes(intent.modifier)) || (intent.toolId==='jpg-to-pdf'&&intent.family==='format'&&intent.modifier==='png-to-pdf') || (intent.toolId==='edit-pdf'&&intent.family==='use-case'&&intent.modifier==='resume');
export function generatePortugueseCandidate(intent: Classification, rows: Keyword[], date: string, previous?: PseoPage): PseoPage|undefined {
 if(!isPortugueseRecipe(intent))return undefined;
 const base=generateCandidate(intent,rows,date,previous);if(!base)return undefined;
 if(intent.toolId==='pdf-to-jpg') {
  const copy=PDF_IMAGE_COPY['pt-BR'];
  const recipes={
   'extract-images': {slug:'extrair-imagens-pdf',title:'Extrair imagens de PDF',intro:'Extraia as imagens raster incorporadas no PDF em suas dimensões nativas decodificadas. Escolha JPG para compartilhar ou PNG para evitar novas perdas na codificação.',details:['Selecione Imagens incorporadas para salvar os elementos de imagem, em vez de capturar páginas inteiras. Uma foto pequena mantém suas próprias dimensões em pixels mesmo quando aparece ampliada no PDF. A resolução de página não aumenta as imagens extraídas.','A extração não mantém o recorte, posicionamento ou composição da página. Desenhos vetoriais e máscaras de estêncil isoladas não são exportados como fotos. Imagens repetidas são salvas uma vez por página. Se não houver imagens raster, a ferramenta informa isso sem substituir o resultado por capturas de páginas.'],steps:['Selecione o PDF e escolha Imagens incorporadas.','Escolha JPG ou PNG; as dimensões nativas são mantidas.','Exporte, baixe a imagem ou o ZIP e confira os elementos separadamente do layout do PDF.']},
   'high-quality': {slug:'pdf-para-jpg-alta-qualidade',title:'PDF para JPG em alta qualidade',intro:'Converta páginas de PDF em imagens a 300 DPI para obter mais definição em textos pequenos e gráficos. Compare JPG com PNG e confira as dimensões exportadas.',details:['Mantenha Páginas completas e Alta definição · 300 DPI selecionados. Uma página A4 gera aproximadamente 2481 × 3508 pixels, dependendo das dimensões exatas do PDF. A 150 DPI, a largura e a altura ficam pela metade.','JPG usa compressão com perdas mesmo na qualidade alta. Para diagramas e textos pequenos, PNG evita os artefatos da compressão JPEG. Aumentar a resolução não recupera detalhes ausentes de uma digitalização desfocada, e o texto deixa de ser selecionável.'],steps:['Selecione os PDFs e mantenha Páginas completas.','Escolha Alta definição · 300 DPI e JPG, ou PNG para codificação de pixels sem perdas.','Exporte e confira os detalhes com zoom de 100%. Várias imagens são entregues em ZIP.']},
   'pdf-to-png': {slug:'pdf-para-png',title:'PDF para PNG',intro:'Exporte páginas de PDF como imagens PNG com codificação de pixels sem perdas. Uma opção para diagramas, capturas de tela e textos sem artefatos de compressão JPEG.',details:['Selecione PNG nos controles de formato. Páginas completas inclui textos e gráficos sobre um fundo branco. Para salvar os elementos raster separados, escolha Imagens incorporadas; a transparência é mantida quando disponível.','PNG não usa a compressão com perdas do JPG, mas a renderização ainda transforma textos e vetores em pixels. Escolha 300 DPI para mais detalhes ou 150 DPI para dimensões menores. Fotos em PNG podem ocupar mais espaço que em JPG.'],steps:['Selecione os PDFs na ferramenta de exportação de imagens.','Escolha PNG e páginas completas ou imagens incorporadas. Ajuste a resolução para páginas completas.','Exporte, baixe e confira as imagens antes de compartilhar ou imprimir.']},
  };
  const recipe=recipes[intent.modifier as keyof typeof recipes];
  const body={h1:recipe.title,subtitle:recipe.intro,intro:recipe.intro,howToSteps:recipe.steps,useCaseContent:recipe.details,compatibilityContent:['DPI indica a densidade de renderização, não a etiqueta de resolução de impressão no arquivo. Confira as dimensões em pixels. Os arquivos são processados no navegador.'],limitationsContent:[copy.qualityNote,copy.extractNote,PDF_IMAGE_LIMITS['pt-BR']],faqItems:[{question:'Como meus arquivos são processados?',answer:copy.privacy},{question:'A qualidade é preservada?',answer:copy.qualityNote}],recipeId:'pt-br-'+base.recipeId};
  return {...base,...body,slug:recipe.slug,language:'pt-BR',locale:'pt-br',metaTitle:recipe.title+' | PDFPilot',metaDescription:recipe.intro,canonicalUrl:'https://pdfpilot.net/pt-br/'+recipe.slug,contentFingerprint:fingerprint(body)};
 }
 const png=intent.modifier==='png-to-pdf',toolHelp=help[png?'jpg-to-pdf':'edit-pdf'];
 const slug=png?'png-para-pdf':'editar-curriculo-pdf';
 const title=png?'PNG para PDF':'Editar currículo em PDF';
 const intro=png?'Transforme capturas de tela e imagens PNG em um PDF. Organize as imagens e confira transparência, margens e tamanho das páginas antes de compartilhar.':'Atualize informações e faça anotações em um currículo PDF. Guarde o original, edite os elementos compatíveis e confira a cópia exportada antes de enviar.';
 const details=png?[
  'PNG é comum em capturas de tela, gráficos e imagens com transparência. Escolha o tamanho ajustado à imagem para manter suas proporções, ou A4 e Carta quando o documento será impresso.',
  'Organize as imagens na ordem de leitura. Confira como as áreas transparentes aparecem no leitor de PDF e verifique se textos pequenos permanecem legíveis. Converter a imagem não recupera detalhes que já foram perdidos.'
 ]:[
  'Antes de mudar datas, contatos ou descrições, salve uma cópia do currículo. Verifique se o texto desejado permite edição. Fontes incorporadas e páginas digitalizadas podem limitar a alteração do conteúdo existente.',
  'Depois de exportar, abra o PDF e confira quebras de linha, espaçamento, número de páginas e informações de contato. Para reorganizar o currículo inteiro, o documento original pode ser mais adequado. Esta ferramenta não avalia compatibilidade com sistemas de recrutamento.'
 ];
 const body={h1:title,subtitle:intro,intro,howToSteps:png?['Selecione as imagens PNG salvas no dispositivo.','Organize as imagens, o tamanho das páginas e as margens.','Converta e confira transparência e legibilidade no PDF baixado.']:['Selecione uma cópia do currículo em PDF.','Faça as alterações compatíveis e revise as áreas modificadas.','Salve, baixe e confira o currículo antes de enviar.'],useCaseContent:details,compatibilityContent:[png?'A ferramenta aceita PNG, JPG e JPEG no mesmo conjunto. Não aceita HEIC, TIFF ou WebP.':'Use os controles existentes para alterações de texto, imagens e anotações. Esta página não cria currículos automaticamente.'],limitationsContent:[toolHelp.limitation],faqItems:[{question:'Como meus arquivos são processados?',answer:toolHelp.privacy},{question:'O que conferir antes de usar o resultado?',answer:toolHelp.limitation}],recipeId:png?'pt-br-png-layout-v1':'pt-br-resume-edits-v1'};
 return {...base,...body,slug:previous?.slug??slug,language:'pt-BR',locale:'pt-br',metaTitle:`${title} | PDFPilot`,metaDescription:intro,canonicalUrl:`https://pdfpilot.net/pt-br/${previous?.slug??slug}`,contentFingerprint:fingerprint(body)};
}
