import { classifyKeyword, normalizeKeyword, type Classification } from './classify';
/** Semantic lexicon for classification, never published machine-translated page copy. */
export function portugueseIntent(input: string): Classification {
 let q=normalizeKeyword(input).normalize('NFD').replace(/[\u0300-\u036f]/g,'');
 const phrases: [RegExp,string][]=[[/\bmarca d agua\b/g,'watermark'],[/\bextratos? bancarios?\b/g,'bank statements'],[/\bsem perder (?:a )?qualidade\b/g,'high quality'],[/\b(?:em|para) um (?:so|unico)\b/g,'into one'],[/\btirar (?:a )?senha\b/g,'unlock'],[/\b(?:adicionar|inserir) (?:uma )?(?:imagem|foto|texto) (?:em|no|ao) (?:um )?pdf\b/g,'add text to pdf'],[/\b(?:numero|numeros|numeracao) de paginas\b/g,'page numbers']];
 for(const [a,b] of phrases)q=q.replace(a,b);
 const words:Record<string,string>={juntarpdf:'merge pdf',apagado:'deleted',excluido:'deleted',escanear:'scan',digitalizador:'scan',assinador:'signature',retirar:'remove',adicionar:'add',inserir:'insert',juntar:'merge',junte:'merge',unificar:'merge',mesclar:'merge',mescle:'merge',agrupar:'merge',unir:'merge',separar:'split',dividir:'split',comprimir:'compress',compactar:'compress',compactador:'compress',compressao:'compress',compactacao:'compress',reduzir:'reduce',diminuir:'reduce',tamanho:'size',transformar:'convert',converter:'convert',conversor:'converter',conversao:'conversion',converta:'convert',transforme:'convert',editar:'edit',editavel:'editable',edicao:'edit',arquivo:'file',arquivos:'files',foto:'photo',fotos:'photos',imagem:'image',imagens:'images',pagina:'page',paginas:'pages',planilha:'spreadsheet',planilhas:'spreadsheets',texto:'text',textos:'text',documento:'document',documentos:'documents',reparar:'repair',recuperar:'recover',consertar:'repair',corrompido:'corrupted',danificado:'damaged',girar:'rotate',rotacionar:'rotate',recortar:'crop',cortar:'crop',organizar:'organize',ordenar:'reorder',numerar:'numbering',preencher:'fill',formulario:'form',formularios:'forms',remover:'remove',excluir:'delete',extrair:'extract',assinatura:'signature',assinar:'sign',senha:'password',desbloquear:'unlock',proteger:'encrypt',traduzir:'translate',tradutor:'translator',traducao:'translation',digitalizar:'scan',digitalizado:'scanned',digitalizados:'scanned',escaneado:'scanned',escaneados:'scanned',pesquisavel:'searchable',curriculo:'resume',paisagem:'landscape',gratuito:'free',gratuita:'free',gratis:'free',portugues:'portuguese',baixar:'download',como:'how',qual:'what',melhor:'best',para:'to',em:'to',no:'in',na:'in',um:'a',uma:'a',de:'',do:'',da:'',os:'',as:'',o:'',a:'',e:'and',sem:'without',com:'with'};
 q=q.split(' ').map(w=>words[w]??w).join(' ').replace(/\s+/g,' ').trim();
 q=q.replace(/\bpdf (scanned|scan|ocr) to (word|docx)\b/g,'$1 pdf to $2');
 const intent=classifyKeyword(q);
 if (intent.family!=='unsupported' && (intent.toolId==='ocr-pdf'||(intent.toolId==='pdf-to-word'&&/scanned|ocr/.test(q))) && !/\benglish\b/.test(q)) return {...intent,family:'unsupported',reason:'portuguese_ocr_language_not_supported',modifier:'portuguese-ocr',signature:`${intent.toolId}:unsupported:portuguese-ocr`};
 return intent;
}
