import type { LocaleCode } from "./locales";
export const CONVERSION_UI_KEYS = ["Ready to convert","Your file is ready","Download PDF again","Download ZIP again","Preparing your files…","Preparing your download…","Building your PDF…","complete","Try Again","One PDF per Word document","Images, tables and visual formatting","Browser-local conversion · nothing is uploaded","Preview updates instantly","No margin","One page per image, in the order shown.","Get one PDF per image in a ZIP file."] as const;
export const CONVERSION_UI_ROWS: Record<Exclude<LocaleCode, "en">, string> = {
  "es": "Listo para convertir|Tu archivo está listo|Descargar PDF de nuevo|Descargar ZIP de nuevo|Preparando tus archivos…|Preparando la descarga…|Creando tu PDF…|completado|Reintentar|Un PDF por documento Word|Imágenes, tablas y formato visual|Conversión local · no se sube nada|La vista previa se actualiza al instante|Sin margen|Una página por imagen, en el orden mostrado.|Un PDF por imagen en un archivo ZIP.",
  "pt-BR": "Pronto para converter|Seu arquivo está pronto|Baixar PDF novamente|Baixar ZIP novamente|Preparando seus arquivos…|Preparando o download…|Criando seu PDF…|concluído|Tentar novamente|Um PDF por documento Word|Imagens, tabelas e formatação visual|Conversão local · nada é enviado|A prévia é atualizada instantaneamente|Sem margem|Uma página por imagem, na ordem mostrada.|Um PDF por imagem em um arquivo ZIP.",
  "de": "Bereit zur Konvertierung|Ihre Datei ist fertig|PDF erneut herunterladen|ZIP erneut herunterladen|Dateien werden vorbereitet…|Download wird vorbereitet…|PDF wird erstellt…|abgeschlossen|Erneut versuchen|Ein PDF pro Word-Dokument|Bilder, Tabellen und visuelle Formatierung|Lokale Konvertierung · kein Upload|Vorschau wird sofort aktualisiert|Ohne Rand|Eine Seite pro Bild in der angezeigten Reihenfolge.|Ein PDF pro Bild in einer ZIP-Datei.",
  "fr": "Prêt à convertir|Votre fichier est prêt|Télécharger à nouveau le PDF|Télécharger à nouveau le ZIP|Préparation des fichiers…|Préparation du téléchargement…|Création de votre PDF…|terminé|Réessayer|Un PDF par document Word|Images, tableaux et mise en forme|Conversion locale · aucun envoi|L’aperçu se met à jour immédiatement|Sans marge|Une page par image, dans l’ordre affiché.|Un PDF par image dans un fichier ZIP.",
  "hi": "कन्वर्ज़न के लिए तैयार|आपकी फ़ाइल तैयार है|PDF फिर डाउनलोड करें|ZIP फिर डाउनलोड करें|फ़ाइलें तैयार हो रही हैं…|डाउनलोड तैयार हो रहा है…|आपका PDF बन रहा है…|पूरा|फिर कोशिश करें|हर Word दस्तावेज़ के लिए एक PDF|चित्र, टेबल और विज़ुअल फ़ॉर्मेटिंग|डिवाइस पर कन्वर्ज़न · कुछ अपलोड नहीं होता|प्रीव्यू तुरंत अपडेट होता है|बिना मार्जिन|दिखाए गए क्रम में हर चित्र का एक पेज।|हर चित्र का अलग PDF, एक ZIP में।",
  "id": "Siap dikonversi|File Anda siap|Unduh PDF lagi|Unduh ZIP lagi|Menyiapkan file…|Menyiapkan unduhan…|Membuat PDF Anda…|selesai|Coba lagi|Satu PDF per dokumen Word|Gambar, tabel dan format visual|Konversi lokal · tanpa unggahan|Pratinjau langsung diperbarui|Tanpa margin|Satu halaman per gambar, sesuai urutan.|Satu PDF per gambar dalam file ZIP.",
  "zh-CN": "准备转换|文件已准备就绪|再次下载 PDF|再次下载 ZIP|正在准备文件…|正在准备下载…|正在创建 PDF…|完成|重试|每个 Word 文档生成一个 PDF|图片、表格和视觉格式|本地转换 · 无需上传|预览即时更新|无边距|每张图片一页，按显示顺序排列。|每张图片生成一个 PDF，打包为 ZIP。",
  "ja": "変換の準備完了|ファイルの準備ができました|PDF を再ダウンロード|ZIP を再ダウンロード|ファイルを準備中…|ダウンロードを準備中…|PDF を作成中…|完了|再試行|Word 文書ごとに一つの PDF|画像、表、視覚的な書式|端末内で変換 · アップロードなし|プレビューを即時更新|余白なし|表示順に画像一枚につき一ページ。|画像ごとの PDF を ZIP にまとめます。",
  "ko": "변환 준비 완료|파일이 준비되었습니다|PDF 다시 다운로드|ZIP 다시 다운로드|파일 준비 중…|다운로드 준비 중…|PDF 생성 중…|완료|다시 시도|Word 문서당 PDF 하나|이미지, 표 및 시각적 서식|기기 내 변환 · 업로드 없음|미리보기 즉시 업데이트|여백 없음|표시된 순서대로 이미지당 한 페이지.|이미지당 PDF 하나를 ZIP으로 묶습니다.",
  "ar": "جاهز للتحويل|ملفك جاهز|تنزيل PDF مجددًا|تنزيل ZIP مجددًا|جارٍ تجهيز الملفات…|جارٍ تجهيز التنزيل…|جارٍ إنشاء PDF…|مكتمل|حاول مجددًا|PDF واحد لكل مستند Word|الصور والجداول والتنسيق المرئي|تحويل محلي · دون رفع ملفات|تتحدث المعاينة فورًا|دون هامش|صفحة لكل صورة بالترتيب المعروض.|PDF لكل صورة ضمن ملف ZIP.",
  "ru": "Готово к преобразованию|Ваш файл готов|Скачать PDF ещё раз|Скачать ZIP ещё раз|Подготовка файлов…|Подготовка скачивания…|Создание PDF…|завершено|Повторить|Один PDF на документ Word|Изображения, таблицы и оформление|Локальное преобразование · без загрузки|Предпросмотр обновляется сразу|Без полей|Одна страница на изображение в указанном порядке.|Один PDF на изображение в ZIP-архиве."
};
export function conversionUiText(locale: LocaleCode, text: string) {
  const index = (CONVERSION_UI_KEYS as readonly string[]).indexOf(text);
  return locale === "en" || index < 0 ? text : CONVERSION_UI_ROWS[locale].split("|")[index];
}
