import type { LocaleCode } from "./locales";

export const HOME_KEYS = [
  "Work your way", "Fast on desktop", "Drop large files, sort them, and finish the task without account friction.",
  "Simple on mobile", "The important action stays obvious, even on a small screen.",
  "Ready for real work", "100MB files, batch workflows, and browser-only processing make it practical.",
  "Built around fewer clicks", "Upload once and move straight into the tool.",
  "Important tools support batches and clear file ordering.", "Downloads are designed to happen automatically after processing.",
  "Trust layer", "Secure. Private. In your control.",
  "Files are processed locally in the browser whenever the tool supports it, so the page stays focused on getting the job done.",
  "No matching tools. Try another search.", "Results", "Tools", "All rights reserved.",
  "Website language", "Changing the website language does not translate your documents.",
] as const;

const ROWS: Record<Exclude<LocaleCode, "en">, string> = {
  es: "Trabaja a tu manera|Rápido en ordenador|Añade archivos grandes, ordénalos y termina sin crear una cuenta.|Sencillo en el móvil|La acción principal sigue clara, incluso en una pantalla pequeña.|Listo para el trabajo|Archivos de 100 MB, procesos por lotes y procesamiento en el navegador.|Menos clics|Añade tu archivo y empieza directamente.|Las herramientas principales permiten lotes y un orden claro de los archivos.|Las descargas están diseñadas para iniciarse al terminar el procesamiento.|Confianza|Seguro. Privado. Bajo tu control.|Cuando la herramienta lo permite, los archivos se procesan localmente en el navegador.|No hay herramientas coincidentes. Prueba otra búsqueda.|Resultados|Herramientas|Todos los derechos reservados.|Idioma del sitio web|Cambiar el idioma del sitio no traduce tus documentos.",
  "pt-BR": "Trabalhe do seu jeito|Rápido no computador|Adicione arquivos grandes, organize-os e conclua sem criar uma conta.|Simples no celular|A ação principal fica clara, mesmo em uma tela pequena.|Pronto para o trabalho|Arquivos de 100 MB, processamento em lote e no navegador.|Menos cliques|Adicione o arquivo e vá direto à ferramenta.|As principais ferramentas permitem lotes e organização clara dos arquivos.|Os downloads foram projetados para iniciar após o processamento.|Confiança|Seguro. Privado. Sob seu controle.|Quando a ferramenta permite, os arquivos são processados localmente no navegador.|Nenhuma ferramenta encontrada. Tente outra busca.|Resultados|Ferramentas|Todos os direitos reservados.|Idioma do site|Mudar o idioma do site não traduz seus documentos.",
  de: "Arbeiten Sie auf Ihre Weise|Schnell am Desktop|Große Dateien hinzufügen, sortieren und ohne Konto fertigstellen.|Einfach auf dem Handy|Die wichtigste Aktion bleibt auch auf kleinen Bildschirmen erkennbar.|Für die Praxis gemacht|100-MB-Dateien, Stapelverarbeitung und Verarbeitung im Browser.|Weniger Klicks|Datei hinzufügen und direkt mit dem Tool beginnen.|Wichtige Tools unterstützen Stapel und eine klare Dateireihenfolge.|Downloads sollen nach der Verarbeitung automatisch starten.|Vertrauen|Sicher. Privat. Unter Ihrer Kontrolle.|Wenn das Tool es unterstützt, werden Dateien lokal im Browser verarbeitet.|Keine passenden Tools. Versuchen Sie eine andere Suche.|Ergebnisse|Tools|Alle Rechte vorbehalten.|Sprache der Website|Die Sprache der Website ändert nicht die Sprache Ihrer Dokumente.",
  fr: "Travaillez à votre façon|Rapide sur ordinateur|Ajoutez de gros fichiers, triez-les et terminez sans créer de compte.|Simple sur mobile|L’action principale reste claire, même sur un petit écran.|Prêt pour le travail|Fichiers de 100 Mo, traitement par lots et dans le navigateur.|Moins de clics|Ajoutez votre fichier et accédez directement à l’outil.|Les outils principaux permettent les lots et un ordre clair des fichiers.|Les téléchargements sont conçus pour démarrer après le traitement.|Confiance|Sécurisé. Privé. Sous votre contrôle.|Lorsque l’outil le permet, les fichiers sont traités localement dans le navigateur.|Aucun outil correspondant. Essayez une autre recherche.|Résultats|Outils|Tous droits réservés.|Langue du site|Changer la langue du site ne traduit pas vos documents.",
  hi: "अपने तरीके से काम करें|डेस्कटॉप पर तेज़|बड़ी फ़ाइलें जोड़ें, क्रम में लगाएँ और बिना अकाउंट बनाए काम पूरा करें।|मोबाइल पर आसान|छोटी स्क्रीन पर भी मुख्य कार्रवाई साफ दिखती है।|काम के लिए तैयार|100 MB फ़ाइलें, बैच वर्कफ़्लो और ब्राउज़र में प्रोसेसिंग।|कम क्लिक में काम|फ़ाइल जोड़ें और सीधे टूल में काम शुरू करें।|प्रमुख टूल बैच और फ़ाइलों के स्पष्ट क्रम को सपोर्ट करते हैं।|प्रोसेसिंग के बाद डाउनलोड अपने-आप शुरू होने के लिए बनाए गए हैं।|भरोसा|सुरक्षित। निजी। आपके नियंत्रण में।|जहाँ टूल सपोर्ट करता है, फ़ाइलें ब्राउज़र में स्थानीय रूप से प्रोसेस होती हैं।|कोई टूल नहीं मिला। दूसरी खोज करें।|नतीजे|टूल|सभी अधिकार सुरक्षित।|वेबसाइट की भाषा|वेबसाइट की भाषा बदलने से आपके दस्तावेज़ों का अनुवाद नहीं होता।",
  id: "Bekerja dengan cara Anda|Cepat di desktop|Tambahkan file besar, urutkan, dan selesaikan tanpa membuat akun.|Mudah di ponsel|Tindakan utama tetap jelas, bahkan di layar kecil.|Siap untuk bekerja|File 100 MB, alur kerja batch, dan pemrosesan di browser.|Lebih sedikit klik|Tambahkan file dan langsung mulai menggunakan alat.|Alat utama mendukung batch dan urutan file yang jelas.|Unduhan dirancang untuk dimulai otomatis setelah pemrosesan.|Kepercayaan|Aman. Privat. Dalam kendali Anda.|Jika alat mendukungnya, file diproses secara lokal di browser.|Tidak ada alat yang cocok. Coba pencarian lain.|Hasil|Alat|Hak cipta dilindungi.|Bahasa situs|Mengubah bahasa situs tidak menerjemahkan dokumen Anda.",
  "zh-CN": "按自己的方式工作|桌面端快速处理|添加大文件、排序，无需创建账户即可完成。|移动端轻松使用|即使在小屏幕上，主要操作也清晰可见。|满足实际工作需要|支持 100 MB 文件、批量工作流程和浏览器内处理。|更少点击|添加文件后直接开始操作。|主要工具支持批量处理和清晰的文件排序。|处理完成后，下载会按设计自动开始。|信任保障|安全、私密，由您掌控。|在工具支持的情况下，文件在浏览器中本地处理。|未找到匹配的工具。请尝试其他搜索。|结果|工具|保留所有权利。|网站语言|更改网站语言不会翻译您的文档。",
  ja: "自分に合った方法で作業|デスクトップで快適に|大きなファイルを追加して並べ替え、アカウントなしで完了できます。|モバイルでも簡単|小さな画面でも主要な操作が分かりやすく表示されます。|実務に対応|100 MB のファイル、一括処理、ブラウザー内処理に対応します。|少ないクリックで完了|ファイルを追加し、そのままツールで作業を始めます。|主要なツールは一括処理と明確なファイル順序に対応します。|処理後にダウンロードが自動で始まるよう設計されています。|信頼の仕組み|安全。プライベート。自分で管理。|対応するツールではファイルをブラウザー内でローカル処理します。|該当するツールがありません。別の語句で検索してください。|検索結果|ツール|無断転載を禁じます。|サイトの言語|サイトの言語を変えても文書は翻訳されません。",
  ko: "나만의 방식으로 작업|데스크톱에서 빠르게|큰 파일을 추가하고 정렬하여 계정 없이 작업을 마칩니다.|모바일에서도 간편하게|작은 화면에서도 주요 작업이 명확하게 보입니다.|실무에 바로 사용|100 MB 파일, 일괄 작업, 브라우저 내 처리를 지원합니다.|더 적은 클릭|파일을 추가하고 바로 도구를 사용하세요.|주요 도구는 일괄 처리와 명확한 파일 정렬을 지원합니다.|처리가 끝나면 다운로드가 자동으로 시작되도록 설계되었습니다.|신뢰|안전하고 비공개이며 직접 제어합니다.|도구가 지원하는 경우 파일은 브라우저에서 로컬로 처리됩니다.|일치하는 도구가 없습니다. 다른 검색어를 입력하세요.|결과|도구|모든 권리 보유.|웹사이트 언어|웹사이트 언어를 변경해도 문서는 번역되지 않습니다.",
  ar: "اعمل بطريقتك|سريع على الكمبيوتر|أضف ملفات كبيرة ورتّبها وأكمل العمل دون إنشاء حساب.|سهل على الهاتف|يبقى الإجراء الأساسي واضحًا حتى على شاشة صغيرة.|جاهز للعمل|ملفات بحجم 100 ميغابايت ومعالجة دفعية وداخل المتصفح.|نقرات أقل|أضف ملفك وابدأ استخدام الأداة مباشرة.|تدعم الأدوات الأساسية الدفعات والترتيب الواضح للملفات.|صُممت التنزيلات لتبدأ تلقائيًا بعد المعالجة.|الثقة|آمن. خاص. تحت سيطرتك.|تتم معالجة الملفات محليًا في المتصفح عندما تدعم الأداة ذلك.|لم يتم العثور على أدوات مطابقة. جرّب بحثًا آخر.|النتائج|الأدوات|جميع الحقوق محفوظة.|لغة الموقع|تغيير لغة الموقع لا يترجم مستنداتك.",
  ru: "Работайте по-своему|Быстро на компьютере|Добавляйте большие файлы, сортируйте и завершайте работу без аккаунта.|Просто на телефоне|Главное действие остаётся заметным даже на маленьком экране.|Готово к работе|Файлы до 100 МБ, пакетные операции и обработка в браузере.|Меньше кликов|Добавьте файл и сразу переходите к работе.|Основные инструменты поддерживают пакеты и понятный порядок файлов.|Загрузка результата должна запускаться автоматически после обработки.|Доверие|Безопасно. Приватно. Под вашим контролем.|Если инструмент поддерживает это, файлы обрабатываются локально в браузере.|Подходящих инструментов нет. Попробуйте другой запрос.|Результаты|Инструменты|Все права защищены.|Язык сайта|Изменение языка сайта не переводит ваши документы.",
};

export function homeText(locale: LocaleCode, text: string): string {
  const index = HOME_KEYS.indexOf(text as typeof HOME_KEYS[number]);
  return locale === "en" || index < 0 ? text : ROWS[locale].split("|")[index];
}
export function validateHomeCopy(): string[] {
  return Object.entries(ROWS).flatMap(([locale, row]) => row.split("|").length === HOME_KEYS.length ? [] : [`${locale}: incomplete homepage copy`]);
}
