import type { LocaleCode } from "./locales";
import { LAUNCH_TOOL_SLUGS } from "../launch-catalog";

// Same supported operations as the English tools. Locale never enters conversion settings.
const SUMMARIES: Record<Exclude<LocaleCode, "en">, string> = {
  es: "Convierte páginas PDF en imágenes JPG o extrae sus imágenes.|Crea un PDF con imágenes JPG y PNG. Ordena las páginas y ajusta el diseño.|Convierte documentos DOCX en PDF, de uno en uno o por lotes.|Convierte presentaciones PPTX en PDF conservando el diseño de las diapositivas.|Convierte hojas de cálculo Excel en PDF.|Convierte páginas web o archivos HTML en PDF.|Extrae el texto de un PDF a un documento Word.|Convierte cada página PDF en una diapositiva de PowerPoint como imagen.|Extrae las tablas de un PDF a Excel.|Crea una copia de archivo PDF/A y revisa las opciones de conversión.|Selecciona y elimina las páginas que no necesitas.|Combina varios PDF en un archivo y elige su orden.|Reduce el tamaño del PDF y ajusta la calidad.|Divide un PDF por páginas o intervalos.|Selecciona y extrae las páginas que necesitas.|Ordena, añade y elimina páginas PDF.|Escanea documentos o importa imágenes para crear un PDF.|Intenta recuperar archivos PDF dañados.|Reconoce texto en PDF escaneados para poder buscarlo.|Gira las páginas de tu PDF.|Añade números de página a tu PDF.|Añade una marca de agua de texto o imagen.|Recorta los márgenes de las páginas PDF.|Añade texto, formas, dibujos y firmas a tu PDF.|Rellena los campos de un formulario PDF.|Convierte hojas de Excel en XML; elige las hojas y las opciones de exportación.",
  "pt-BR": "Converta páginas PDF em JPG ou extraia suas imagens.|Crie um PDF com imagens JPG e PNG. Organize as páginas e ajuste o layout.|Converta documentos DOCX em PDF, individualmente ou em lote.|Converta apresentações PPTX em PDF preservando o layout dos slides.|Converta planilhas Excel em PDF.|Converta páginas da web ou arquivos HTML em PDF.|Extraia o texto de um PDF para um documento Word.|Transforme cada página PDF em um slide do PowerPoint como imagem.|Extraia tabelas de um PDF para o Excel.|Crie uma cópia de arquivo PDF/A e confira as opções de conversão.|Selecione e remova as páginas desnecessárias.|Combine vários PDFs em um arquivo e escolha a ordem.|Reduza o tamanho do PDF e ajuste a qualidade.|Divida um PDF por páginas ou intervalos.|Selecione e extraia as páginas necessárias.|Organize, adicione e remova páginas PDF.|Digitalize documentos ou importe imagens para criar um PDF.|Tente recuperar arquivos PDF danificados.|Reconheça o texto de PDFs digitalizados para permitir buscas.|Gire as páginas do seu PDF.|Adicione números de página ao PDF.|Adicione uma marca d’água de texto ou imagem.|Recorte as margens das páginas PDF.|Adicione texto, formas, desenhos e assinaturas ao PDF.|Preencha os campos de um formulário PDF.|Converta planilhas Excel em XML; escolha as planilhas e opções de exportação.",
  de: "PDF-Seiten in JPG umwandeln oder enthaltene Bilder extrahieren.|Aus JPG- und PNG-Bildern ein PDF erstellen, Seiten ordnen und das Layout wählen.|DOCX-Dokumente einzeln oder im Stapel in PDF umwandeln.|PPTX-Präsentationen unter Beibehaltung des Folienlayouts in PDF umwandeln.|Excel-Tabellen in PDF umwandeln.|Webseiten oder HTML-Dateien in PDF umwandeln.|Text aus einem PDF in ein Word-Dokument extrahieren.|Jede PDF-Seite als Bild auf eine PowerPoint-Folie übertragen.|Tabellen aus einem PDF nach Excel extrahieren.|Eine PDF/A-Archivkopie erstellen und die Konvertierungsoptionen prüfen.|Nicht benötigte Seiten auswählen und entfernen.|Mehrere PDFs in der gewünschten Reihenfolge zusammenfügen.|PDF-Dateien verkleinern und die Qualität einstellen.|Ein PDF nach Seiten oder Bereichen teilen.|Gewünschte Seiten auswählen und extrahieren.|PDF-Seiten sortieren, hinzufügen und löschen.|Dokumente scannen oder Bilder importieren und ein PDF erstellen.|Beschädigte PDF-Dateien zu reparieren versuchen.|Text in gescannten PDFs erkennen und durchsuchbar machen.|Die Seiten Ihres PDFs drehen.|Seitenzahlen zu Ihrem PDF hinzufügen.|Ein Wasserzeichen aus Text oder einem Bild hinzufügen.|Die Ränder der PDF-Seiten zuschneiden.|Text, Formen, Zeichnungen und Unterschriften zum PDF hinzufügen.|Die Felder eines PDF-Formulars ausfüllen.|Excel-Tabellen in XML umwandeln; Blätter und Exportoptionen auswählen.",
  fr: "Convertissez les pages PDF en JPG ou extrayez leurs images.|Créez un PDF à partir d’images JPG et PNG. Organisez les pages et choisissez la mise en page.|Convertissez des documents DOCX en PDF, seuls ou par lots.|Convertissez des présentations PPTX en PDF en conservant la disposition des diapositives.|Convertissez des feuilles de calcul Excel en PDF.|Convertissez des pages web ou des fichiers HTML en PDF.|Extrayez le texte d’un PDF dans un document Word.|Transformez chaque page PDF en image sur une diapositive PowerPoint.|Extrayez les tableaux d’un PDF dans Excel.|Créez une copie d’archivage PDF/A et vérifiez les options de conversion.|Sélectionnez et supprimez les pages inutiles.|Combinez plusieurs PDF dans l’ordre souhaité.|Réduisez la taille du PDF et réglez la qualité.|Divisez un PDF par pages ou par plages.|Sélectionnez et extrayez les pages souhaitées.|Triez, ajoutez et supprimez des pages PDF.|Numérisez des documents ou importez des images pour créer un PDF.|Tentez de récupérer des fichiers PDF endommagés.|Reconnaissez le texte des PDF numérisés pour permettre la recherche.|Faites pivoter les pages de votre PDF.|Ajoutez des numéros de page à votre PDF.|Ajoutez un filigrane texte ou image.|Recadrez les marges des pages PDF.|Ajoutez du texte, des formes, des dessins et des signatures au PDF.|Remplissez les champs d’un formulaire PDF.|Convertissez des feuilles Excel en XML ; choisissez les feuilles et les options d’exportation.",
  hi: "PDF के पेज JPG में बदलें या उसमें मौजूद चित्र निकालें।|JPG और PNG चित्रों से PDF बनाएँ। पेज का क्रम और लेआउट चुनें।|DOCX दस्तावेज़ों को अलग-अलग या बैच में PDF में बदलें।|PPTX प्रस्तुति को स्लाइड के लेआउट के साथ PDF में बदलें।|Excel स्प्रेडशीट को PDF में बदलें।|वेब पेज या HTML फ़ाइल को PDF में बदलें।|PDF का टेक्स्ट Word दस्तावेज़ में निकालें।|हर PDF पेज को चित्र के रूप में PowerPoint स्लाइड में बदलें।|PDF की टेबल Excel में निकालें।|PDF/A संग्रह प्रति बनाएँ और कन्वर्ज़न विकल्प देखें।|अनचाहे पेज चुनें और हटाएँ।|कई PDF को मनचाहे क्रम में एक फ़ाइल में जोड़ें।|PDF का आकार कम करें और गुणवत्ता चुनें।|PDF को पेज या पेज-रेंज के अनुसार बाँटें।|ज़रूरी पेज चुनें और निकालें।|PDF के पेज क्रम में लगाएँ, जोड़ें और हटाएँ।|दस्तावेज़ स्कैन करें या चित्र जोड़कर PDF बनाएँ।|खराब PDF फ़ाइल को सुधारने की कोशिश करें।|स्कैन किए PDF का टेक्स्ट पहचानकर खोजने योग्य बनाएँ।|अपने PDF के पेज घुमाएँ।|PDF में पेज नंबर जोड़ें।|टेक्स्ट या चित्र का वॉटरमार्क जोड़ें।|PDF पेज के मार्जिन क्रॉप करें।|PDF में टेक्स्ट, आकृतियाँ, ड्रॉइंग और हस्ताक्षर जोड़ें।|PDF फ़ॉर्म के फ़ील्ड भरें।|Excel शीट को XML में बदलें; शीट और एक्सपोर्ट विकल्प चुनें।",
  id: "Ubah halaman PDF menjadi JPG atau ekstrak gambarnya.|Buat PDF dari gambar JPG dan PNG. Atur urutan halaman dan tata letaknya.|Konversi dokumen DOCX ke PDF satu per satu atau sekaligus.|Konversi presentasi PPTX ke PDF dengan mempertahankan tata letak slide.|Konversi spreadsheet Excel ke PDF.|Konversi halaman web atau file HTML ke PDF.|Ekstrak teks PDF ke dokumen Word.|Jadikan setiap halaman PDF sebagai gambar pada slide PowerPoint.|Ekstrak tabel PDF ke Excel.|Buat salinan arsip PDF/A dan periksa opsi konversinya.|Pilih dan hapus halaman yang tidak diperlukan.|Gabungkan beberapa PDF dengan urutan yang Anda pilih.|Kurangi ukuran PDF dan sesuaikan kualitasnya.|Pisahkan PDF berdasarkan halaman atau rentang.|Pilih dan ekstrak halaman yang diperlukan.|Urutkan, tambah, dan hapus halaman PDF.|Pindai dokumen atau impor gambar untuk membuat PDF.|Coba pulihkan file PDF yang rusak.|Kenali teks dalam PDF hasil pindai agar dapat dicari.|Putar halaman PDF Anda.|Tambahkan nomor halaman ke PDF.|Tambahkan tanda air teks atau gambar.|Pangkas margin halaman PDF.|Tambahkan teks, bentuk, gambar, dan tanda tangan ke PDF.|Isi kolom formulir PDF.|Konversi lembar Excel ke XML; pilih lembar dan opsi ekspornya.",
  "zh-CN": "将 PDF 页面转换为 JPG，或提取其中的图片。|用 JPG 和 PNG 图片创建 PDF，调整页面顺序和布局。|将 DOCX 文档单独或批量转换为 PDF。|将 PPTX 演示文稿转换为 PDF，保留幻灯片布局。|将 Excel 电子表格转换为 PDF。|将网页或 HTML 文件转换为 PDF。|将 PDF 文本提取到 Word 文档。|将每个 PDF 页面作为图片放入 PowerPoint 幻灯片。|将 PDF 表格提取到 Excel。|创建 PDF/A 存档副本，并检查转换选项。|选择并删除不需要的页面。|按所需顺序将多个 PDF 合并为一个文件。|减小 PDF 文件大小并调整质量。|按页面或页码范围拆分 PDF。|选择并提取所需页面。|排序、添加和删除 PDF 页面。|扫描文档或导入图片以创建 PDF。|尝试修复损坏的 PDF 文件。|识别扫描 PDF 中的文字，使其可搜索。|旋转 PDF 页面。|为 PDF 添加页码。|添加文字或图片水印。|裁剪 PDF 页面的边距。|为 PDF 添加文字、形状、绘图和签名。|填写 PDF 表单字段。|将 Excel 工作表转换为 XML，选择工作表和导出选项。",
  ja: "PDF のページを JPG に変換するか、含まれる画像を抽出します。|JPG と PNG から PDF を作成し、ページ順とレイアウトを選びます。|DOCX 文書を単独または一括で PDF に変換します。|PPTX をスライドのレイアウトを保った PDF に変換します。|Excel の表を PDF に変換します。|ウェブページや HTML ファイルを PDF に変換します。|PDF のテキストを Word 文書に抽出します。|PDF の各ページを画像として PowerPoint のスライドに変換します。|PDF の表を Excel に抽出します。|PDF/A のアーカイブ用コピーを作成し、変換オプションを確認します。|不要なページを選択して削除します。|複数の PDF を指定した順序で一つに結合します。|PDF のファイルサイズを減らし、品質を調整します。|ページまたは範囲を指定して PDF を分割します。|必要なページを選択して抽出します。|PDF のページを並べ替え、追加、削除します。|文書をスキャンするか画像を取り込んで PDF を作成します。|破損した PDF ファイルの修復を試みます。|スキャンした PDF の文字を認識し、検索できるようにします。|PDF のページを回転します。|PDF にページ番号を追加します。|文字や画像の透かしを追加します。|PDF ページの余白を切り取ります。|PDF に文字、図形、描画、署名を追加します。|PDF フォームの入力欄を記入します。|Excel シートを XML に変換し、シートと出力オプションを選びます。",
  ko: "PDF 페이지를 JPG로 변환하거나 포함된 이미지를 추출합니다.|JPG와 PNG로 PDF를 만들고 페이지 순서와 레이아웃을 선택합니다.|DOCX 문서를 개별 또는 일괄로 PDF로 변환합니다.|슬라이드 레이아웃을 유지하여 PPTX를 PDF로 변환합니다.|Excel 스프레드시트를 PDF로 변환합니다.|웹 페이지나 HTML 파일을 PDF로 변환합니다.|PDF 텍스트를 Word 문서로 추출합니다.|각 PDF 페이지를 이미지로 PowerPoint 슬라이드에 넣습니다.|PDF 표를 Excel로 추출합니다.|PDF/A 보관용 사본을 만들고 변환 옵션을 확인합니다.|필요 없는 페이지를 선택하고 삭제합니다.|여러 PDF를 원하는 순서로 하나의 파일로 병합합니다.|PDF 파일 크기를 줄이고 품질을 조정합니다.|페이지나 범위를 지정하여 PDF를 분할합니다.|필요한 페이지를 선택하고 추출합니다.|PDF 페이지를 정렬하고 추가하거나 삭제합니다.|문서를 스캔하거나 이미지를 가져와 PDF를 만듭니다.|손상된 PDF 파일의 복구를 시도합니다.|스캔한 PDF의 텍스트를 인식하여 검색할 수 있게 합니다.|PDF 페이지를 회전합니다.|PDF에 페이지 번호를 추가합니다.|텍스트 또는 이미지 워터마크를 추가합니다.|PDF 페이지의 여백을 자릅니다.|PDF에 텍스트, 도형, 그림, 서명을 추가합니다.|PDF 양식의 필드를 작성합니다.|Excel 시트를 XML로 변환하고 시트와 내보내기 옵션을 선택합니다.",
  ar: "حوّل صفحات PDF إلى JPG أو استخرج الصور الموجودة فيها.|أنشئ PDF من صور JPG وPNG واختر ترتيب الصفحات وتخطيطها.|حوّل مستندات DOCX إلى PDF منفردة أو دفعة واحدة.|حوّل عروض PPTX إلى PDF مع الحفاظ على تخطيط الشرائح.|حوّل جداول Excel إلى PDF.|حوّل صفحات الويب أو ملفات HTML إلى PDF.|استخرج نص PDF إلى مستند Word.|حوّل كل صفحة PDF إلى صورة داخل شريحة PowerPoint.|استخرج جداول PDF إلى Excel.|أنشئ نسخة أرشيف PDF/A وراجع خيارات التحويل.|اختر الصفحات غير المطلوبة واحذفها.|ادمج عدة ملفات PDF في ملف واحد بالترتيب المطلوب.|قلّل حجم PDF واضبط الجودة.|قسّم PDF حسب الصفحات أو النطاقات.|اختر الصفحات المطلوبة واستخرجها.|رتّب صفحات PDF وأضفها واحذفها.|امسح المستندات أو استورد صورًا لإنشاء PDF.|حاول إصلاح ملفات PDF التالفة.|تعرّف على النص في ملفات PDF الممسوحة لجعله قابلًا للبحث.|دوّر صفحات PDF.|أضف أرقام الصفحات إلى PDF.|أضف علامة مائية نصية أو صورية.|قص هوامش صفحات PDF.|أضف نصوصًا وأشكالًا ورسومات وتوقيعات إلى PDF.|املأ حقول نموذج PDF.|حوّل أوراق Excel إلى XML واختر الأوراق وخيارات التصدير.",
  ru: "Преобразуйте страницы PDF в JPG или извлеките встроенные изображения.|Создайте PDF из JPG и PNG, задайте порядок страниц и макет.|Преобразуйте документы DOCX в PDF по одному или пакетом.|Преобразуйте PPTX в PDF с сохранением макета слайдов.|Преобразуйте таблицы Excel в PDF.|Преобразуйте веб-страницы или HTML-файлы в PDF.|Извлеките текст PDF в документ Word.|Преобразуйте каждую страницу PDF в изображение на слайде PowerPoint.|Извлеките таблицы PDF в Excel.|Создайте архивную копию PDF/A и проверьте параметры преобразования.|Выберите и удалите ненужные страницы.|Объедините несколько PDF в нужном порядке.|Уменьшите размер PDF и настройте качество.|Разделите PDF по страницам или диапазонам.|Выберите и извлеките нужные страницы.|Сортируйте, добавляйте и удаляйте страницы PDF.|Сканируйте документы или импортируйте изображения для создания PDF.|Попробуйте восстановить повреждённые PDF.|Распознайте текст сканированных PDF для поиска.|Поверните страницы PDF.|Добавьте номера страниц в PDF.|Добавьте текстовый или графический водяной знак.|Обрежьте поля страниц PDF.|Добавьте текст, фигуры, рисунки и подписи в PDF.|Заполните поля формы PDF.|Преобразуйте листы Excel в XML, выберите листы и параметры экспорта.",
};

export function localizedToolSummary(slug: string, locale: LocaleCode, fallback: string): string {
  if (locale === "en") return fallback;
  const index = LAUNCH_TOOL_SLUGS.indexOf(slug);
  return index < 0 ? fallback : SUMMARIES[locale].split("|")[index];
}

export function validateToolSummaries(): string[] {
  return Object.entries(SUMMARIES).flatMap(([locale, row]) => row.split("|").length === LAUNCH_TOOL_SLUGS.length ? [] : [`${locale}: incomplete tool descriptions`]);
}
