import type { LocaleCode } from "./locales";

const KEYS = ["Change file", "Choose a Different File", "Start over", "Preview your pages", "Preview updates as you choose", "Color", "Reset all", "Page size", "Margin", "Pages", "Clear selection", "Select pages", "Select all", "Position", "Text", "Text format", "Image quality", "Normal", "Recommended", "High", "Extract images", "Page to JPG", "Convert to JPG", "PDF options", "Page orientation", "Merge all images in one PDF", "Download PDF", "Use camera", "Step 1", "Step 2", "Waiting for images", "Select scan images", "Use your phone camera, scanner app, or saved photos.", "After you add photos, choose page orientation, size, margins, then save them as a PDF.", "Upload from your computer", "Rendering page previews…", "Select HTML file", "Website URL", "Your workbooks", "Add", "Save", "Convert", "Orientation", "Portrait", "Landscape", "Auto", "Fit", "None", "Small", "Big"] as const;
const ROWS: Record<Exclude<LocaleCode, "en">, string> = {
  es: "Cambiar archivo|Elegir otro archivo|Empezar de nuevo|Vista previa de las páginas|La vista previa se actualiza al elegir|Color|Restablecer todo|Tamaño de página|Margen|Páginas|Borrar selección|Seleccionar páginas|Seleccionar todo|Posición|Texto|Formato del texto|Calidad de imagen|Normal|Recomendado|Alta|Extraer imágenes|Página a JPG|Convertir a JPG|Opciones PDF|Orientación de página|Unir todas las imágenes en un PDF|Descargar PDF|Usar cámara|Paso 1|Paso 2|Esperando imágenes|Seleccionar imágenes escaneadas|Usa la cámara del móvil, una aplicación de escáner o fotos guardadas.|Añade fotos, elige la orientación, el tamaño y los márgenes, y guárdalas como PDF.|Añadir desde tu ordenador|Generando vistas previas…|Seleccionar archivo HTML|URL del sitio web|Tus libros de cálculo|Añadir|Guardar|Convertir|Orientación|Vertical|Horizontal|Automático|Ajustar|Ninguno|Pequeño|Grande",
  "pt-BR": "Trocar arquivo|Escolher outro arquivo|Recomeçar|Prévia das páginas|A prévia acompanha suas escolhas|Cor|Redefinir tudo|Tamanho da página|Margem|Páginas|Limpar seleção|Selecionar páginas|Selecionar tudo|Posição|Texto|Formato do texto|Qualidade da imagem|Normal|Recomendado|Alta|Extrair imagens|Página para JPG|Converter para JPG|Opções do PDF|Orientação da página|Juntar todas as imagens em um PDF|Baixar PDF|Usar câmera|Etapa 1|Etapa 2|Aguardando imagens|Selecionar imagens digitalizadas|Use a câmera do celular, um aplicativo de scanner ou fotos salvas.|Adicione fotos, escolha a orientação, o tamanho e as margens e salve como PDF.|Adicionar do computador|Gerando prévias…|Selecionar arquivo HTML|URL do site|Suas pastas de trabalho|Adicionar|Salvar|Converter|Orientação|Retrato|Paisagem|Automático|Ajustar|Nenhum|Pequeno|Grande",
  de: "Datei wechseln|Andere Datei wählen|Neu beginnen|Seitenvorschau|Die Vorschau folgt Ihrer Auswahl|Farbe|Alles zurücksetzen|Seitengröße|Rand|Seiten|Auswahl aufheben|Seiten auswählen|Alle auswählen|Position|Text|Textformat|Bildqualität|Normal|Empfohlen|Hoch|Bilder extrahieren|Seite in JPG|In JPG umwandeln|PDF-Optionen|Seitenausrichtung|Alle Bilder in einem PDF zusammenfügen|PDF herunterladen|Kamera verwenden|Schritt 1|Schritt 2|Warten auf Bilder|Scanbilder auswählen|Verwenden Sie die Handykamera, eine Scanner-App oder gespeicherte Fotos.|Fügen Sie Fotos hinzu, wählen Sie Ausrichtung, Größe und Ränder und speichern Sie als PDF.|Vom Computer hinzufügen|Seitenvorschauen werden erstellt…|HTML-Datei auswählen|Website-URL|Ihre Arbeitsmappen|Hinzufügen|Speichern|Konvertieren|Ausrichtung|Hochformat|Querformat|Automatisch|Anpassen|Keine|Klein|Groß",
  fr: "Changer de fichier|Choisir un autre fichier|Recommencer|Aperçu des pages|L’aperçu suit vos choix|Couleur|Tout réinitialiser|Taille de page|Marge|Pages|Effacer la sélection|Sélectionner les pages|Tout sélectionner|Position|Texte|Format du texte|Qualité d’image|Normale|Recommandé|Élevée|Extraire les images|Page en JPG|Convertir en JPG|Options PDF|Orientation de page|Fusionner toutes les images dans un PDF|Télécharger le PDF|Utiliser la caméra|Étape 1|Étape 2|En attente d’images|Sélectionner les images numérisées|Utilisez la caméra du téléphone, une application de numérisation ou des photos enregistrées.|Ajoutez des photos, choisissez l’orientation, la taille et les marges, puis enregistrez en PDF.|Ajouter depuis l’ordinateur|Création des aperçus…|Sélectionner un fichier HTML|URL du site|Vos classeurs|Ajouter|Enregistrer|Convertir|Orientation|Portrait|Paysage|Automatique|Ajuster|Aucune|Petite|Grande",
  hi: "फ़ाइल बदलें|दूसरी फ़ाइल चुनें|फिर से शुरू करें|अपने पेज का प्रीव्यू|विकल्प चुनते ही प्रीव्यू बदलता है|रंग|सब रीसेट करें|पेज का आकार|मार्जिन|पेज|चयन हटाएँ|पेज चुनें|सभी चुनें|स्थिति|टेक्स्ट|टेक्स्ट फ़ॉर्मेट|चित्र की गुणवत्ता|सामान्य|सुझाया गया|उच्च|चित्र निकालें|पेज से JPG|JPG में बदलें|PDF विकल्प|पेज की दिशा|सभी चित्र एक PDF में जोड़ें|PDF डाउनलोड करें|कैमरा इस्तेमाल करें|चरण 1|चरण 2|चित्रों का इंतज़ार|स्कैन किए चित्र चुनें|फ़ोन का कैमरा, स्कैनर ऐप या सेव किए फ़ोटो इस्तेमाल करें।|फ़ोटो जोड़ें, पेज की दिशा, आकार और मार्जिन चुनें, फिर PDF सेव करें।|कंप्यूटर से जोड़ें|पेज प्रीव्यू बन रहा है…|HTML फ़ाइल चुनें|वेबसाइट URL|आपकी वर्कबुक|जोड़ें|सेव करें|बदलें|दिशा|पोर्ट्रेट|लैंडस्केप|अपने-आप|फ़िट|कोई नहीं|छोटा|बड़ा",
  id: "Ganti file|Pilih file lain|Mulai lagi|Pratinjau halaman|Pratinjau mengikuti pilihan Anda|Warna|Atur ulang semua|Ukuran halaman|Margin|Halaman|Hapus pilihan|Pilih halaman|Pilih semua|Posisi|Teks|Format teks|Kualitas gambar|Normal|Disarankan|Tinggi|Ekstrak gambar|Halaman ke JPG|Konversi ke JPG|Opsi PDF|Orientasi halaman|Gabungkan semua gambar dalam satu PDF|Unduh PDF|Gunakan kamera|Langkah 1|Langkah 2|Menunggu gambar|Pilih gambar hasil pindai|Gunakan kamera ponsel, aplikasi pemindai, atau foto tersimpan.|Tambahkan foto, pilih orientasi, ukuran, dan margin, lalu simpan sebagai PDF.|Tambahkan dari komputer|Membuat pratinjau halaman…|Pilih file HTML|URL situs web|Buku kerja Anda|Tambah|Simpan|Konversi|Orientasi|Potret|Lanskap|Otomatis|Sesuaikan|Tidak ada|Kecil|Besar",
  "zh-CN": "更换文件|选择其他文件|重新开始|页面预览|预览随选项更新|颜色|全部重置|页面大小|边距|页面|清除选择|选择页面|全选|位置|文字|文字格式|图像质量|普通|推荐|高|提取图片|页面转 JPG|转换为 JPG|PDF 选项|页面方向|将所有图片合并为一个 PDF|下载 PDF|使用摄像头|第 1 步|第 2 步|等待图片|选择扫描图片|使用手机摄像头、扫描应用或保存的照片。|添加照片后，选择方向、大小和边距，再保存为 PDF。|从电脑添加|正在生成页面预览…|选择 HTML 文件|网站 URL|您的工作簿|添加|保存|转换|方向|纵向|横向|自动|适应|无|小|大",
  ja: "ファイルを変更|別のファイルを選択|最初からやり直す|ページのプレビュー|選択に合わせてプレビューを更新|色|すべてリセット|ページサイズ|余白|ページ|選択を解除|ページを選択|すべて選択|位置|テキスト|テキスト形式|画質|標準|推奨|高|画像を抽出|ページを JPG に変換|JPG に変換|PDF オプション|ページの向き|すべての画像を一つの PDF に結合|PDF をダウンロード|カメラを使う|手順 1|手順 2|画像を待っています|スキャン画像を選択|スマートフォンのカメラ、スキャナーアプリ、保存済み写真を使います。|写真を追加し、向き、サイズ、余白を選んで PDF として保存します。|コンピューターから追加|ページのプレビューを作成中…|HTML ファイルを選択|ウェブサイトの URL|ワークブック|追加|保存|変換|向き|縦|横|自動|合わせる|なし|小|大",
  ko: "파일 변경|다른 파일 선택|다시 시작|페이지 미리보기|선택에 따라 미리보기 업데이트|색상|모두 초기화|페이지 크기|여백|페이지|선택 해제|페이지 선택|모두 선택|위치|텍스트|텍스트 형식|이미지 품질|일반|권장|높음|이미지 추출|페이지를 JPG로|JPG로 변환|PDF 옵션|페이지 방향|모든 이미지를 하나의 PDF로 병합|PDF 다운로드|카메라 사용|1단계|2단계|이미지 대기 중|스캔 이미지 선택|휴대폰 카메라, 스캐너 앱 또는 저장된 사진을 사용하세요.|사진을 추가하고 방향, 크기, 여백을 선택한 후 PDF로 저장하세요.|컴퓨터에서 추가|페이지 미리보기 생성 중…|HTML 파일 선택|웹사이트 URL|내 통합 문서|추가|저장|변환|방향|세로|가로|자동|맞춤|없음|작게|크게",
  ar: "تغيير الملف|اختيار ملف آخر|البدء من جديد|معاينة الصفحات|تتحدث المعاينة حسب اختياراتك|اللون|إعادة تعيين الكل|حجم الصفحة|الهامش|الصفحات|مسح التحديد|اختيار الصفحات|تحديد الكل|الموضع|النص|تنسيق النص|جودة الصورة|عادية|موصى به|عالية|استخراج الصور|صفحة إلى JPG|تحويل إلى JPG|خيارات PDF|اتجاه الصفحة|دمج كل الصور في PDF واحد|تنزيل PDF|استخدام الكاميرا|الخطوة 1|الخطوة 2|بانتظار الصور|اختيار صور المسح|استخدم كاميرا الهاتف أو تطبيق ماسح ضوئي أو صورًا محفوظة.|أضف الصور واختر اتجاه الصفحة وحجمها وهوامشها ثم احفظها كملف PDF.|إضافة من الكمبيوتر|جارٍ إنشاء معاينة الصفحات…|اختيار ملف HTML|رابط الموقع|مصنفاتك|إضافة|حفظ|تحويل|الاتجاه|عمودي|أفقي|تلقائي|ملاءمة|بلا|صغير|كبير",
  ru: "Сменить файл|Выбрать другой файл|Начать заново|Предпросмотр страниц|Предпросмотр обновляется при выборе|Цвет|Сбросить всё|Размер страницы|Поля|Страницы|Снять выделение|Выбрать страницы|Выбрать всё|Положение|Текст|Формат текста|Качество изображения|Обычное|Рекомендуется|Высокое|Извлечь изображения|Страница в JPG|Конвертировать в JPG|Параметры PDF|Ориентация страницы|Объединить все изображения в один PDF|Скачать PDF|Использовать камеру|Шаг 1|Шаг 2|Ожидание изображений|Выбрать сканы|Используйте камеру телефона, приложение сканера или сохранённые фотографии.|Добавьте фотографии, выберите ориентацию, размер и поля, затем сохраните PDF.|Добавить с компьютера|Создание предпросмотра…|Выбрать HTML-файл|URL сайта|Ваши книги|Добавить|Сохранить|Конвертировать|Ориентация|Книжная|Альбомная|Авто|По размеру|Нет|Маленькие|Большие",
};

export function workspaceText(locale: LocaleCode, text: string): string {
  const normalized = text === "Start Over" ? "Start over" : text;
  const index = KEYS.indexOf(normalized as typeof KEYS[number]);
  return locale === "en" || index < 0 ? text : ROWS[locale].split("|")[index];
}
export function validateWorkspaceCopy(): string[] {
  return Object.entries(ROWS).flatMap(([locale, row]) => row.split("|").length === KEYS.length ? [] : [`${locale}: incomplete workspace copy`]);
}
