import Link from "next/link";
import { notFound } from "next/navigation";
import { PDF_WORKFLOWS, getPdfWorkflow, workflowPath } from "@/lib/content/pdf-workflows";
import { pseoMetadata } from "@/lib/content/pseo-metadata";
import { TOOLS } from "@/lib/tools";
import { PdfWorkflowRunner } from "@/components/templates/PdfWorkflowRunner";
import { JsonLd } from "@/components/seo/JsonLd";
import { getBreadcrumbSchema } from "@/lib/seo";
import { TrackContentOpened } from "@/components/content/TrackContentOpened";
type Props = { params: Promise<{ slug: string }> };
export const dynamicParams = false;
export function generateStaticParams() { return PDF_WORKFLOWS.map(row => ({ slug: row.slug })); }
export async function generateMetadata({ params }: Props) { const row = getPdfWorkflow((await params).slug); return row ? pseoMetadata(row.title, row.description, workflowPath(row), `/template-samples/workflows/${row.slug}.png`) : {}; }
export default async function Page({ params }: Props) {
  const row = getPdfWorkflow((await params).slug); if (!row) notFound();
  return <div className="container mx-auto max-w-6xl px-4 py-10"><TrackContentOpened contentType="workflow" contentId={row.slug} /><JsonLd data={[getBreadcrumbSchema([{ name: "PDFPilot", path: "/" }, { name: "PDF workflows", path: "/pdf-workflows" }, { name: row.title, path: workflowPath(row) }]), { "@context": "https://schema.org", "@type": "SoftwareApplication", name: row.title, description: row.description, url: `https://pdfpilot.net${workflowPath(row)}`, applicationCategory: "UtilitiesApplication", operatingSystem: "Web browser", inLanguage: "en", offers: { "@type": "Offer", price: "0", priceCurrency: "USD" } }]} />
    <Link href="/pdf-workflows" className="text-sm underline">All PDF workflows</Link><header className="my-8 grid items-center gap-8 md:grid-cols-[1.2fr_1fr]"><div><p className="text-sm font-semibold text-primary">{row.input.toUpperCase()} → PDF · Two steps in one flow</p><h1 className="mt-3 text-3xl font-bold tracking-tight md:text-5xl">{row.title}</h1><p className="mt-5 text-lg text-muted-foreground">{row.description}</p><a href="#runner" className="mt-6 inline-block rounded-xl bg-primary px-5 py-3 font-semibold text-primary-foreground">Start this workflow</a></div><figure className="rounded-2xl border bg-muted/30 p-4">
      {/* eslint-disable-next-line @next/next/no-img-element -- generated from the actual workflow result */}
      <img src={`/template-samples/workflows/${row.slug}.png`} alt={`First page of the ${row.title} sample result`} width={595} height={842} className="h-72 w-full object-contain" /><figcaption className="mt-3 text-center text-xs text-muted-foreground">Actual sample result · first page. Try the sample below to inspect every page.</figcaption></figure></header>
    <ol className="mb-8 grid gap-3 sm:grid-cols-2">{row.steps.map((step, i) => <li key={step} className="rounded-xl border p-4"><span className="mr-3 text-primary">{i + 1}.</span>{step}</li>)}</ol><PdfWorkflowRunner workflow={row} />
    <div className="mt-10 grid gap-10 lg:grid-cols-[1fr_300px]"><div className="space-y-8"><section><h2 className="text-xl font-semibold">When to use this workflow</h2><p className="mt-3 leading-relaxed text-muted-foreground">{row.purpose}</p></section><section><h2 className="text-xl font-semibold">Check the result</h2><ul className="mt-3 list-disc space-y-3 ps-5">{row.checks.map(check => <li key={check}>{check}</li>)}</ul></section><section className="rounded-xl border bg-muted/30 p-5"><h2 className="text-xl font-semibold">Supported files and limits</h2><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{row.limitations}</p></section><section><h2 className="text-xl font-semibold">{row.question}</h2><p className="mt-3 text-muted-foreground">{row.answer}</p></section></div><aside className="space-y-8"><nav aria-label="Individual workflow tools"><h2 className="font-semibold">Use each tool separately</h2><ul className="mt-3 space-y-3">{row.tools.map(slug => <li key={slug}><Link href={`/${slug}`} className="text-sm underline">{TOOLS.find(tool => tool.slug === slug)?.name}</Link></li>)}</ul></nav><section><h2 className="font-semibold">Download sample inputs</h2><ul className="mt-3 space-y-3">{row.samples.map(name => <li key={name}><a href={`/template-samples/${name}`} download className="text-sm underline">{name}</a></li>)}</ul><p className="mt-3 text-xs text-muted-foreground">Original demonstration files. No customer documents.</p></section><nav aria-label="Related PDF workflows"><h2 className="font-semibold">Related workflows</h2><ul className="mt-3 space-y-3">{PDF_WORKFLOWS.filter(other => other.slug !== row.slug && other.tools.some(tool => row.tools.includes(tool))).slice(0, 4).map(other => <li key={other.slug}><Link href={workflowPath(other)} className="text-sm underline">{other.title}</Link></li>)}</ul></nav></aside></div></div>;
}
